
const Dlist=[{Firstname:"meet",
    No:20,
    age:60,
    id:0,
    email:"www.jok@1321321",
    Lastname:"shah"
},{
    Firstname:"deep",
    No:20,
    age:70,
    id:1,
    email:"www.jok@1321321",
    Lastname:"shah"
},{
    Firstname:"smith",
    No:20,
    age:60,
    id:2,
    email:"www.jok@1321321",
    Lastname:"Marvadi"
},
    {
        Firstname:"Meenit",
        No:22,
        age:55,
        id:3,
        email:"www.jok@1321321",
        Lastname:"Pandit"
    },{
        Firstname:"Harish",
        No:23,
        age:85,
        id:4,
        email:"www.jok@1321321",
        Lastname:"shah"
    },{
        Firstname:"Het",
        No:26,
        age:60,
        id:5,
        email:"www.jok@1321321",
        Lastname:"Dave"
    },{
        Firstname:"Jaiyanti",
        No:29,
        age:70,
        id:6,
        email:"www.jok@1321321",
        Lastname:"Dave"
    },{
        Firstname:"Narendra",
        No:21,
        age:80,
        id:7,
        email:"www.jok@1321321",
        Lastname:"Pandit"
    },{
        Firstname:"Jugal",
        No:18,
        age:99,
        id:8,
        email:"www.jok@1321321",
        Lastname:"Dave"
    },{
        Firstname:"Priyansh",
        No:16,
        age:19,
        id:9,
        email:"www.jok@1321321",
        Lastname:"shah"
    }]
export default Dlist;